// ...existing code...
document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('registerForm');
  const qrcodeContainer = document.getElementById('qrcode');

  function clearQRCode() {
    qrcodeContainer.innerHTML = '';
  }

  function makeDownloadLink() {
    // try to find canvas or img generated by qrcodejs
    const canvas = qrcodeContainer.querySelector('canvas');
    const img = qrcodeContainer.querySelector('img');

    let dataURL = null;
    if (canvas) dataURL = canvas.toDataURL('image/png');
    else if (img) dataURL = img.src;

    if (!dataURL) return;

    const existingLink = document.getElementById('downloadQR');
    if (existingLink) existingLink.remove();

    const a = document.createElement('a');
    a.id = 'downloadQR';
    a.href = dataURL;
    a.download = `qr_${Date.now()}.png`;
    a.textContent = 'Download QR';
    a.style.display = 'inline-block';
    a.style.marginTop = '10px';
    qrcodeContainer.appendChild(a);
  }

  form.addEventListener('submit', (e) => {
    e.preventDefault();

    const fullName = document.getElementById('fullName').value.trim();
    const email = document.getElementById('email').value.trim();
    const phone = document.getElementById('phone').value.trim();
    const purpose = document.getElementById('purpose').value.trim();

    if (!fullName || !email || !phone || !purpose) {
      alert('Please fill all fields.');
      return;
    }

    // Build payload for QR (change format if you prefer plain text)
    const payload = {
      name: fullName,
      email,
      phone,
      purpose,
      registeredAt: new Date().toISOString()
    };

    clearQRCode();

    // Generate QR code
    new QRCode(qrcodeContainer, {
      text: JSON.stringify(payload),
      width: 220,
      height: 220,
      colorDark: "#000000",
      colorLight: "#ffffff",
      correctLevel: QRCode.CorrectLevel.H
    });

    // Save attendance record to localStorage
    try {
      const records = JSON.parse(localStorage.getItem('attendance') || '[]');
      records.push({
        fullName,
        email,
        phone,
        purpose,
        time: new Date().toLocaleString(),
        registeredAt: payload.registeredAt
      });
      localStorage.setItem('attendance', JSON.stringify(records));
    } catch (err) {
      console.error('Failed to save attendance', err);
    }

    // clear form inputs
    form.reset();

    // Wait a tick for QR to be rendered, then create download link
    setTimeout(makeDownloadLink, 200);
  });
});
